services:
  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    hostname: silverbullet
    restart: unless-stopped
    volumes:
      - /zssd/notes:/space
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
