---
services: 
  webtop:
    image: lscr.io/linuxserver/webtop:alpine-icewm
    container_name: webtop
    hostname: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TITLE=Webtop # website name in browser
    restart: no
    expose:
      - 3000 # http
    volumes:
     #- /zssd/docker_data/webtop/home_persistent:/config/persistent
     #- /zssd/docker_data/webtop/home:/config
      - /mnt/nfs/media:/media
    shm_size: "4gb" # set larger shared memory size
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
