--- 
services:
  audiobookshelf:
    image: advplyr/audiobookshelf
    user: "1000:1000"
    container_name: audiobookshelf
    hostname: audiobookshelf
    restart: unless-stopped
    volumes:
      - /zssd/docker_data/audiobookshelf/config:/config
      - /zssd/docker_data/audiobookshelf/metadata:/metadata
      - /mnt/nfs/media/audiobooks/audiobookshelf:/audiobooks
      - /mnt/nfs/media/podcasts/ashelf_casts:/podcasts
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
