services:
  pairdrop: 
    image: "lscr.io/linuxserver/pairdrop:latest" 
    container_name: pairdrop 
    hostname: pairdrop
    restart: unless-stopped 
    environment: 
      - PUID=1000
      - PGID=1000
      - WS_FALLBACK=true
      - RATE_LIMIT=true # Set to true to limit clients to 1000 requests per 5 min. 
      - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers. 
      - DEBUG_MODE=false # Set to true to debug container and peer connections. 
      - TZ=America/Chicago
    expose: 
      - "3000"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
