---
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Chicago'
      - RATE_LIMIT=true
      - WS_FALLBACK=true
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
